baseURL:                    "http://minimalismus-tipps.de"
languageCode:               "de-de"
title:                      "Minimalismus Tipps"
description:                "Tipps von Minimalismus-Bloggern"